## Phase I: construction of gene candidate pool by DEA
+ This notebooks is where we filtered DEA results which comes from Phase I. We used [GEO2R](https://www.ncbi.nlm.nih.gov/geo/geo2r/) for DEA of our [GSE252168 Study](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE252168). Raw DEA dataset coming from GEO2R is stored as [GSE252168.top.table](../data/GSE252168/GSE252168.top.table.tsv) in the data folder.

In [1]:
import pandas as pd

In [ ]:
# Number of samples: 303 (123 lung cancer patients, 180 controls)
dea_results = pd.read_csv("../data/GSE252168.top.table.tsv", sep="\t")
print(dea_results.shape)
dea_results.head()

(30715, 9)

,ID,adj.P.Val,P.Value,t,B,logFC,GI,Gene.symbol,Gene.title
0,ILMN_1898691,7.550000e-57,2.460000e-61,21.071059,128.844380,0.448859,27832370.0,NaN,NaN
1,ILMN_1769409,8.750000e-55,5.700000e-59,20.437210,123.455995,0.478773,968121855.0,TMEM261,transmembrane protein 261
2,ILMN_1769277,1.470000e-54,1.440000e-58,20.329924,122.540990,1.611407,NaN,NaN,NaN
3,ILMN_1762769,1.640000e-54,2.140000e-58,20.283997,122.149042,0.654262,749502360.0,POLR2J4,"RNA polymerase II subunit J4, pseudogene"
4,ILMN_3200661,6.170000e-53,1.000000e-56,19.838450,118.339374,1.731515,NaN,NaN,NaN

In [3]:
# Remove entries where we are missing Gene Symbol since we cannot use them later via PPI network
dea_df1 = dea_results[dea_results["Gene.symbol"].notna()].copy()
# Also apply threshold '0.05' for adjusted p values
dea_df2 = dea_df1[dea_df1["adj.P.Val"] < 0.05].copy()
print(dea_df2.shape)
dea_df2.head()

(14044, 9)

,ID,adj.P.Val,P.Value,t,B,logFC,GI,Gene.symbol,Gene.title
1,ILMN_1769409,8.750000e-55,5.700000e-59,20.437210,123.455995,0.478773,968121855.0,TMEM261,transmembrane protein 261
3,ILMN_1762769,1.640000e-54,2.140000e-58,20.283997,122.149042,0.654262,749502360.0,POLR2J4,"RNA polymerase II subunit J4, pseudogene"
5,ILMN_1750507,2.420000e-51,4.740000e-55,19.393764,114.524919,1.555679,985482503.0,RPL9,ribosomal protein L9
10,ILMN_1754195,2.030000e-48,8.300000e-52,18.535141,107.131843,1.620676,153252117.0,RPL31,ribosomal protein L31
11,ILMN_1787949,2.030000e-48,8.530000e-52,18.531924,107.104086,1.282546,71772414.0,RPS15A,ribosomal protein S15a

In [ ]:
# Save filtered DEA result by modifying the column order
# dea_df2 = dea_df2.iloc[:, [0,7,8,1,2,5,3,4,6]]
# dea_df2.drop(columns=["t","B","GI","Gene.title"]).to_csv("../data/dea_filtered.tsv", sep= "\t",index=False)