### run this notebook

# Phase VI Part 3: biological function and pathway enrichment analysis 
+ In this notebook, genes that were identified via DEA after filtering for false discovery rate-adjusted P -value (0.05), and expression fold change (FC) exceeding a (commonly |logFC| >= 1).

In [2]:
import gseapy as gp
import pandas as pd
import json

In [3]:
# Upload DEA result to further filter via logFC 
dea_df = pd.read_csv("../data/GSE252168/dea_filtered.tsv", sep="\t")
print(dea_df.shape)
dea_df.head()

(14044, 5)

             ID Gene.symbol     adj.P.Val       P.Value     logFC
0  ILMN_1769409     TMEM261  8.750000e-55  5.700000e-59  0.478773
1  ILMN_1762769     POLR2J4  1.640000e-54  2.140000e-58  0.654262
2  ILMN_1750507        RPL9  2.420000e-51  4.740000e-55  1.555679
3  ILMN_1754195       RPL31  2.030000e-48  8.300000e-52  1.620676
4  ILMN_1787949      RPS15A  2.030000e-48  8.530000e-52  1.282546

In [4]:
# Get only the genes with logGC is equal or higher than 1
dea_df = dea_df[dea_df["logFC"] >= 1]
print(dea_df.shape)
dea_df.head()

(30, 5)

             ID Gene.symbol     adj.P.Val       P.Value     logFC
2  ILMN_1750507        RPL9  2.420000e-51  4.740000e-55  1.555679
3  ILMN_1754195       RPL31  2.030000e-48  8.300000e-52  1.620676
4  ILMN_1787949      RPS15A  2.030000e-48  8.530000e-52  1.282546
7  ILMN_2207539       RPS17  1.060000e-46  5.540000e-50  1.144404
8  ILMN_1656807       RPL27  1.630000e-46  9.100000e-50  1.151581

In [5]:
gene_list = list(dea_df["Gene.symbol"])
n = len(gene_list)

In [3]:
# Upload GO gmt file
go_set = "../data/enrichment/go.gmt"
kegg_set = "../data/enrichment/kegg.gmt"

In [4]:
# Upload the GO Terms and KEGG Term Mappings
kegg_map = open("../data/enrichment/kegg_mapping.json")
go_map = open(("../data/enrichment/go_mapping.json"))
kegg_terms_mapping = json.load(kegg_map)
go_term_mapping = json.load(go_map)

In [5]:
enr_go = gp.enrich(gene_list=dice_genes_v2, 
                 gene_sets=go_set, 
                 background=None,
                 outdir=None,
                 verbose=True)

2026-03-05 14:08:26,438 [INFO] User defined gene sets is given: ../data/enrichment/go.gmt
2026-03-05 14:08:26,592 [INFO] Run: go.gmt
2026-03-05 14:08:35,568 [INFO]   Background is not set! Use all 19591 genes in go.gmt.
2026-03-05 14:08:37,237 [INFO] Done.

In [6]:
enr_go.results.head()

,Gene_set,Term,Overlap,P-value,Adjusted P-value,Odds Ratio,Combined Score,Genes
0,go.gmt,GO:0000014,1/12,0.596593,0.727585,1.659900,0.857373,DCLRE1C
1,go.gmt,GO:0000018,24/141,0.000080,0.000860,2.681222,25.291023,TFRC;BCL6;UBQLN4;MBTD1;SKP2;PTPRC;KPNA1;MRGBP;...
2,go.gmt,GO:0000019,1/7,0.411092,0.607984,2.937556,2.611307,MLH1
3,go.gmt,GO:0000022,1/12,0.596593,0.727585,1.659900,0.857373,RACGAP1
4,go.gmt,GO:0000027,8/29,0.000836,0.006153,5.053196,35.813641,MRM2;NOP2;BOP1;RPF2;RPL24;RPL11;RPL5;MDN1

In [7]:
# Save the results to a new df
results_go = enr_go.results
results_go.head()

,Gene_set,Term,Overlap,P-value,Adjusted P-value,Odds Ratio,Combined Score,Genes
0,go.gmt,GO:0000014,1/12,0.596593,0.727585,1.659900,0.857373,DCLRE1C
1,go.gmt,GO:0000018,24/141,0.000080,0.000860,2.681222,25.291023,TFRC;BCL6;UBQLN4;MBTD1;SKP2;PTPRC;KPNA1;MRGBP;...
2,go.gmt,GO:0000019,1/7,0.411092,0.607984,2.937556,2.611307,MLH1
3,go.gmt,GO:0000022,1/12,0.596593,0.727585,1.659900,0.857373,RACGAP1
4,go.gmt,GO:0000027,8/29,0.000836,0.006153,5.053196,35.813641,MRM2;NOP2;BOP1;RPF2;RPL24;RPL11;RPL5;MDN1

In [8]:
# Filter out results with less than 0.05 adjusted p value
results_go_filt = results_go[results_go['Adjusted P-value'] < 0.05].copy()
print(f"Number of significant results: {len(results_go_filt)}")
results_go_filt.head()

Number of significant results: 1789

,Gene_set,Term,Overlap,P-value,Adjusted P-value,Odds Ratio,Combined Score,Genes
1,go.gmt,GO:0000018,24/141,0.000080,0.000860,2.681222,25.291023,TFRC;BCL6;UBQLN4;MBTD1;SKP2;PTPRC;KPNA1;MRGBP;...
4,go.gmt,GO:0000027,8/29,0.000836,0.006153,5.053196,35.813641,MRM2;NOP2;BOP1;RPF2;RPL24;RPL11;RPL5;MDN1
5,go.gmt,GO:0000028,8/24,0.000199,0.001830,6.586282,56.141828,RPS27L;METTL17;RPS27;FAU;RPS6;RPS14;PRKDC;RPSA
9,go.gmt,GO:0000049,19/81,0.000004,0.000062,4.009925,49.670637,FARS2;TRMT1;XPO5;EEF1A1;EIF2A;EIF1AX;PUS1;EIF2...
11,go.gmt,GO:0000055,3/7,0.010802,0.049081,9.915643,44.898295,NUP88;RAN;SDAD1

In [9]:
# Map GO terms id to descriptions
results_go_filt["GO Term Name"] = results_go_filt["Term"].map(go_term_mapping)

In [10]:
# Add new overlap column and calculate the overlap ratio
results_go_filt["new_overlap"] = results_go_filt["Overlap"].str.split("/").str[0] + "/1453"
results_go_filt["new_overlap_rat"] = results_go_filt["Overlap"].apply(lambda x: int(x.split("/")[0]) / n)

# Reorder the df
results_go_filt = results_go_filt.iloc[:, [0, 1, 8, 9, 10,2,3,4,5,6,7]]

In [11]:
# Sort the results based on new overlap ratio
results_go_filt.sort_values("new_overlap_rat", ascending=False, inplace=True)

In [12]:
# Check the final df 
results_go_filt.head()

,Gene_set,Term,GO Term Name,new_overlap,new_overlap_rat,Overlap,P-value,Adjusted P-value,Odds Ratio,Combined Score,Genes
4373,go.gmt,GO:0043933,protein-containing complex organization,279/1453,0.192017,279/1964,1.113099e-29,3.114758e-27,2.379392,158.628910,DKC1;MDM2;PTK2B;TSPYL6;VTI1B;RPF2;LAMP2;TWF2;S...
7094,go.gmt,GO:0140513,nuclear protein-containing complex,277/1453,0.190640,277/1445,2.221954e-54,2.253895e-51,3.508384,433.430022,DKC1;CPSF4;RFC3;SMAD3;KDM6B;NOP58;HNRNPH1;EXOS...
4435,go.gmt,GO:0044419,biological process involved in interspecies in...,274/1453,0.188575,274/1918,1.620720e-29,4.384048e-27,2.390639,158.480494,PSMC2;FYN;IGF2R;GRN;SMAD3;HK1;LAMP2;CD80;SIRPA...
927,go.gmt,GO:0005739,mitochondrion,272/1453,0.187199,272/1782,3.304807e-34,1.489917e-31,2.600204,200.456268,FARS2;FYN;MRPL17;HK1;MRPL42;MRPL11;SLC25A28;AB...
3461,go.gmt,GO:0033554,cellular response to stress,268/1453,0.184446,268/1984,5.640222e-25,9.535500e-23,2.218993,123.896845,MDM2;PTK2B;FYN;CFLAR;RFC3;GRN;DNAJB9;KDM6B;LAM...

In [ ]:
# # Save GO encrichment analysis results
# results_go_filt.to_csv("../data/enrichment/dice_v2_go_results.tsv", sep="\t", index=False)

### Part 2: KEGG pathway enrichment analysis

In [14]:
enr_kegg = gp.enrich(gene_list=dice_genes_v2, 
                 gene_sets=kegg_set, 
                 background=None,
                 outdir=None,
                 verbose=True)

2026-03-05 14:08:37,463 [INFO] User defined gene sets is given: ../data/enrichment/kegg.gmt
2026-03-05 14:08:37,468 [INFO] Run: kegg.gmt
2026-03-05 14:08:37,498 [INFO]   Background is not set! Use all 8011 genes in kegg.gmt.
2026-03-05 14:08:37,572 [INFO] Done.

In [15]:
# Save the results to a new df
results_kegg = enr_kegg.results
results_kegg.head()

,Gene_set,Term,Overlap,P-value,Adjusted P-value,Odds Ratio,Combined Score,Genes
0,kegg.gmt,hsa00010,9/68,0.371262,0.616773,1.241076,1.229718,ACSS2;HK1;GAPDH;ALDOA;ENO2;ENO3;AKR1A1;PGAM1;LDHA
1,kegg.gmt,hsa00020,1/30,0.973782,1.000000,0.393449,0.010453,FH
2,kegg.gmt,hsa00030,6/30,0.119380,0.256170,2.065650,4.390422,ALDOA;TKT;PGD;TALDO1;PRPS1;G6PD
3,kegg.gmt,hsa00040,1/34,0.983884,1.000000,0.346274,0.005626,AKR1A1
4,kegg.gmt,hsa00051,4/33,0.529217,0.760596,1.184235,0.753596,HK1;ALDOA;TSTA3;ENOSF1

In [16]:
# Filter out results with less than 0.05 adjusted p value
results_kegg_filt = results_kegg[results_kegg['Adjusted P-value'] < 0.05].copy()
print(f"Number of significant results: {len(results_kegg_filt)}")
results_kegg_filt.head()

Number of significant results: 95

,Gene_set,Term,Overlap,P-value,Adjusted P-value,Odds Ratio,Combined Score,Genes
14,kegg.gmt,hsa00190,29/133,3.954995e-04,0.002003,2.229522,17.469109,ATP6V0D1;COX7A2L;NDUFA6;COX6A1;UQCRQ;COX7C;ATP...
71,kegg.gmt,hsa01521,20/79,4.174335e-04,0.002080,2.711045,21.095683,GRB2;RPS6;BAX;MTOR;HGF;BCL2L11;GSK3B;PRKCB;STA...
72,kegg.gmt,hsa01522,20/96,5.209736e-03,0.019164,2.103497,11.058561,MDM2;GRB2;E2F1;CARM1;BAX;MTOR;MAPK14;NOTCH3;NO...
74,kegg.gmt,hsa01524,16/73,7.159778e-03,0.025141,2.248545,11.106183,MAP3K5;MDM2;PMAIP1;ATM;FASLG;BIRC3;APAF1;CASP3...
75,kegg.gmt,hsa03008,32/108,2.027086e-07,0.000004,3.380159,52.093306,DKC1;DROSHA;EFL1;NXF1;GNL3L;NOP58;IMP3;UTP14C;...

In [17]:
# Map GO terms id to descriptions
results_kegg_filt["KEGG Pathway"] = results_kegg_filt["Term"].map(kegg_terms_mapping)

In [18]:
# Add new overlap column and calculate the overlap ratio
results_kegg_filt["new_overlap"] = results_kegg_filt["Overlap"].str.split("/").str[0] + "/1453"
results_kegg_filt["new_overlap_rat"] = results_kegg_filt["Overlap"].apply(lambda x: int(x.split("/")[0]) / n)

# Reorder the df
results_kegg_filt = results_kegg_filt.iloc[:, [0, 1, 8, 9, 10,2,3,4,5,6,7]]

In [19]:
# Sort the results based on new overlap ratio
results_kegg_filt.sort_values("new_overlap_rat", ascending=False, inplace=True)

In [20]:
# Check the final df
results_kegg_filt.head()

,Gene_set,Term,KEGG Pathway,new_overlap,new_overlap_rat,Overlap,P-value,Adjusted P-value,Odds Ratio,Combined Score,Genes
271,kegg.gmt,hsa05200,Pathways in cancer - Homo sapiens (human),99/1453,0.068135,99/531,2.689709e-07,5.522655e-06,1.880380,28.447642,MDM2;SMAD3;CSF3R;E2F1;NOTCH3;NOTCH1;GSK3B;IKBK...
76,kegg.gmt,hsa03010,Ribosome - Homo sapiens (human),85/1453,0.058500,85/158,1.009782e-39,3.120226e-37,9.850943,884.526844,MRPL17;MRPL11;RPS16;RPL39;RPS29;MRPL16;RPL17;R...
233,kegg.gmt,hsa05010,Alzheimer disease - Homo sapiens (human),81/1453,0.055747,81/369,2.259462e-09,1.163623e-07,2.307924,45.946462,PSMC2;CSNK1A1;PPP3CB;NDUFA8;NDUFB8;NDUFS5;CSNK...
236,kegg.gmt,hsa05016,Huntington disease - Homo sapiens (human),64/1453,0.044047,64/306,7.449372e-07,1.192219e-05,2.143941,30.250931,PSMC2;NDUFB2;GNAQ;COX7A2L;PSMD6;SOD2;NDUFA6;PS...
247,kegg.gmt,hsa05131,Shigellosis - Homo sapiens (human),62/1453,0.042670,62/242,3.336378e-10,2.577352e-08,2.809685,61.310032,MDM2;CAPN1;ATM;HK1;TLR5;RRAGB;CAPNS1;UBE2D2;WA...

In [ ]:
# # Save the kegg encrichment results
# results_kegg_filt.to_csv("../data/enrichment/dice_v2_kegg_results.tsv", sep="\t", index=False)