# Phase II: selection of most discriminative genes using IG

## Part 1: IG Calculation
- Further filter the gene pool by taking only those genes with IG higher than the mean IG of all genes.

In [ ]:
import pandas as pd

from sklearn.feature_selection import mutual_info_classif

In [ ]:
# Get class info from id maping to health status
health_stat = pd.read_csv("../data/GSE252168/id_to_health_status.tsv", sep= "\t", usecols=[1])
health_stat.head()

    Status
0  control
1  control
2  control
3  control
4  control

In [ ]:
# Get the class labels
y = health_stat["Status"]

In [ ]:
y

0      control
1      control
2      control
3      control
4      control
        ...
298    control
299    control
300    control
301    control
302    control
Name: Status, Length: 303, dtype: str

In [ ]:
# Upload the expression matrix and prepare for the mutual_info_classif function
expression_df = pd.read_csv("../data/GSE252168/row_filtered.tsv", sep="\t")
expression_df.drop("ID_REF", axis=1, inplace=True)
expression_df.head()

,ILMN_1762337,ILMN_1736007,ILMN_2383229,ILMN_1814316,ILMN_1668111,ILMN_1755321,ILMN_1698554,ILMN_1760414,ILMN_2061446,ILMN_1668851,...,ILMN_1779783,ILMN_1685547,ILMN_2348512,ILMN_1743643,ILMN_1656676,ILMN_2371169,ILMN_1701875,ILMN_1786396,ILMN_1653618,ILMN_2137536
0,6.601397,6.555132,6.563006,6.538115,6.487908,6.502019,6.467476,6.593454,7.114948,6.344277,...,6.636482,6.493231,6.816312,7.070625,8.129110,9.825466,10.612416,7.642387,7.119752,7.073798
1,6.477026,6.640189,6.738270,6.554947,6.451093,6.499183,6.552973,6.554356,6.955625,6.395458,...,6.501612,6.540461,6.792972,7.196791,8.405085,9.505995,10.615032,7.826965,7.222498,6.656577
2,6.528409,6.500988,6.645548,6.461470,6.333161,6.616165,6.701698,6.446938,6.879105,6.454641,...,6.682851,6.710829,6.909647,7.253427,8.306038,9.562776,10.077904,7.853563,7.465050,6.800421
3,6.547416,6.509216,6.628310,6.569797,6.313699,6.506304,6.822026,6.600196,7.172154,6.450936,...,6.587851,6.581868,6.848492,7.400357,8.434583,10.452790,10.550622,7.974522,7.269712,6.603563
4,6.623571,6.498857,6.607876,6.574199,6.391719,6.490693,6.538222,6.563677,6.966809,6.430273,...,6.745439,6.529034,6.891276,7.013339,8.154735,9.235334,9.891232,7.617143,7.320744,7.174409

In [ ]:
# create the matrix for mutual_info_classif function
X = expression_df.values

In [ ]:
# Calculate IG for each gene and assign the expression matrix as dense by setting discrete_features to False
ig_results = mutual_info_classif(X, y, discrete_features=False)

In [ ]:
# Calculate the average IG for whole gene population
pop_mean = ig_results.mean()
print(f"The average IG for the gene pool population is {pop_mean:2f}")

The average IG for the gene pool population is 0.071058

In [ ]:
# Create a df to store IG values of the genes
ig_result_df = pd.DataFrame([ig_results], columns=expression_df.columns)
ig_result_df.head()

,ILMN_1762337,ILMN_1736007,ILMN_2383229,ILMN_1814316,ILMN_1668111,ILMN_1755321,ILMN_1698554,ILMN_1760414,ILMN_2061446,ILMN_1668851,...,ILMN_1779783,ILMN_1685547,ILMN_2348512,ILMN_1743643,ILMN_1656676,ILMN_2371169,ILMN_1701875,ILMN_1786396,ILMN_1653618,ILMN_2137536
0,0.058405,0.082485,0.045625,0.079398,0.176929,0.030019,0.013105,0.073541,0.064791,0.179462,...,0.024358,0.11743,0.16496,0.047723,0.083551,0.13124,0.224093,0.093285,0.221991,0.100968

In [ ]:
# Get the genes where their IG is higher than the average IG
filt_genes = ig_result_df.loc[:, ig_result_df.iloc[0]>=pop_mean]
filt_genes = filt_genes.transpose().rename(columns={0:"IG_value"})

In [ ]:
# Check how many genes filtered after IG 
print(f"The number of genes before IG filtration: {expression_df.shape[1]}")
print(f"The number of genes after IG filtration: {filt_genes.shape[0]}")

The number of genes before IG filtration: 14044
The number of genes after IG filtration: 5608

In [ ]:
# # Save the result 
# filt_genes.to_csv("../data/GSE252168/IG_results.tsv", sep="\t")

## Part 2: Map the selected genes to HGNC symbols

In [ ]:
# Upload the DEA result table to get gene symbols for corresponding gene IDs
dea_df = pd.read_csv("../data/GSE252168/dea_filtered.tsv", sep="\t", usecols=[0,1])
dea_df.head()

             ID Gene.symbol
0  ILMN_1769409     TMEM261
1  ILMN_1762769     POLR2J4
2  ILMN_1750507        RPL9
3  ILMN_1754195       RPL31
4  ILMN_1787949      RPS15A

In [ ]:
# Create a dict where we have mapping from gene id to gene symbol
gene_id_to_symbol = dict(zip(dea_df["ID"], dea_df["Gene.symbol"]))
print(gene_id_to_symbol)

{'ILMN_1769409': 'TMEM261', 'ILMN_1762769': 'POLR2J4', 'ILMN_1750507': 'RPL9', 'ILMN_1754195': 'RPL31', 'ILMN_1787949': 'RPS15A', 'ILMN_3236713': 'SNHG1', 'ILMN_3245458': 'SNORA61', 'ILMN_2207539': 'RPS17', 'ILMN_1656807': 'RPL27', 'ILMN_2207533': 'RPS17', 'ILMN_1777378': 'COMMD6', 'ILMN_2369785': 'SNRPD2', 'ILMN_1659786': 'TRMT13', 'ILMN_1677239': 'CCDC14', 'ILMN_1681846': 'ZNF540', 'ILMN_3251662': 'HINT3', 'ILMN_2315569': 'N6AMT1', 'ILMN_1663160': 'ZNF337', 'ILMN_1737015': 'RPL39', 'ILMN_1807710': 'HINT1', 'ILMN_1676842': 'BTAF1', 'ILMN_2318725': 'EEF1B2', 'ILMN_1652594': 'ACTR5', 'ILMN_2383097': 'RPL17', 'ILMN_1712678': 'RPS27L', 'ILMN_1710078': 'TMEM181', 'ILMN_2145518': 'TMEM126B', 'ILMN_2192385': 'TTC19', 'ILMN_1806106': 'GNL3', 'ILMN_1776181': 'BIRC3', 'ILMN_1695362': 'ZNF32', 'ILMN_1733050': 'SEC31B', 'ILMN_1812478': 'ZNHIT3', 'ILMN_1694587': 'EEF1B2', 'ILMN_2119774': 'CYP2R1', 'ILMN_1755536': 'PFDN5', 'ILMN_1797425': 'DDX55', 'ILMN_1756360': 'RPL35A', 'ILMN_2087060': 'TOMM7', 'ILMN_2227195': 'CCDC65', 'ILMN_1706873': 'RPL34', 'ILMN_1660498': 'RPS27', 'ILMN_1656625': 'RPS24', 'ILMN_1798189': 'COX7C', 'ILMN_1669259': 'ANKRD49', 'ILMN_1770339': 'RPAIN', 'ILMN_1783333': 'CMC2', 'ILMN_2175465': 'RSL24D1', 'ILMN_2079655': 'KLRB1', 'ILMN_1772113': 'U2AF1', 'ILMN_1666635': 'RPS14', 'ILMN_2400183': 'DPH5', 'ILMN_1674069': 'TOMM7', 'ILMN_1750101': 'S100A11', 'ILMN_1683562': 'SNRPG', 'ILMN_2316806': 'RWDD1', 'ILMN_2213199': 'CEP44', 'ILMN_1770048': 'DPH5', 'ILMN_2201533': 'TMEM256', 'ILMN_1732182': 'FBXO44', 'ILMN_1675156': 'CDC42', 'ILMN_2182750': 'DDX1', 'ILMN_1796407': 'SS18L2', 'ILMN_1702526': 'ADPRM', 'ILMN_2117330': 'NDUFB2', 'ILMN_1716730': 'BOD1', 'ILMN_1803036': 'TARBP1', 'ILMN_1669927': 'ICOS', 'ILMN_2325837': 'CD3D', 'ILMN_1712298': 'ANKRD46', 'ILMN_1679382': 'CCT2', 'ILMN_1654151': 'COX6C', 'ILMN_3242315': 'SNORD3D', 'ILMN_1728710': 'ZNF816', 'ILMN_1676302': 'PCED1A', 'ILMN_1758728': 'FANCG', 'ILMN_1904135': 'LOC102725126///FRG1HP', 'ILMN_1686367': 'HSPA8', 'ILMN_1788024': 'PCID2', 'ILMN_1733690': 'AKAP7', 'ILMN_1774973': 'SNORD21', 'ILMN_1689445': 'POLR2H', 'ILMN_1731546': 'RPL26', 'ILMN_1712155': 'RPL6', 'ILMN_1689747': 'NOL8', 'ILMN_1706305': 'COX16', 'ILMN_1855746': 'VPS13A', 'ILMN_1691097': 'HSP90AA1', 'ILMN_2261416': 'CD3D', 'ILMN_1678165': 'LSM7', 'ILMN_2415634': 'TTN', 'ILMN_1777066': 'NIF3L1', 'ILMN_2255310': 'RPS15A', 'ILMN_1690392': 'COMMD3', 'ILMN_1734867': 'NR2C1', 'ILMN_1664424': 'ZBED5', 'ILMN_1686135': 'CEP95', 'ILMN_1798533': 'ZNF22', 'ILMN_1774083': 'TRIAP1', 'ILMN_1802973': 'ANAPC4', 'ILMN_3235404': 'SNORA57', 'ILMN_1780773': 'LINC00938', 'ILMN_1676946': 'AP3M2', 'ILMN_2190414': 'ZNF83', 'ILMN_1661945': 'SLIRP', 'ILMN_1707783': 'TMA7', 'ILMN_2391765': 'C6orf48', 'ILMN_1697469': 'SRSF6', 'ILMN_1774823': 'RPL34', 'ILMN_2068435': 'ZNF700', 'ILMN_1789364': 'ZNF789', 'ILMN_1671728': 'CARD14', 'ILMN_1763605': 'DIDO1', 'ILMN_1731644': 'SETDB2', 'ILMN_1749432': 'MRPL32', 'ILMN_1683065': 'COA5', 'ILMN_1766851': 'TMEM126B', 'ILMN_3228822': 'NEMP1', 'ILMN_1759411': 'BRICD5', 'ILMN_1716272': 'KBTBD8', 'ILMN_1696466': 'ROPN1L', 'ILMN_3222974': 'PRKCB', 'ILMN_1771238': 'CHM', 'ILMN_1736814': 'CLNS1A', 'ILMN_1698406': 'ORMDL1', 'ILMN_1655422': 'RPL17', 'ILMN_2108938': 'FNBP4', 'ILMN_1701293': 'COX7A2', 'ILMN_1666471': 'UQCRQ', 'ILMN_1757604': 'TPM2', 'ILMN_2126706': 'LMNB1', 'ILMN_3237679': 'PTAR1', 'ILMN_2142815': 'RPL35', 'ILMN_2117904': 'ZNF22', 'ILMN_2294878': 'NSUN5', 'ILMN_1808584': 'COX20', 'ILMN_1732725': 'PPP6R3', 'ILMN_1676010': 'SP1', 'ILMN_3251565': 'RNASEH2C', 'ILMN_2126423': 'ZNF480', 'ILMN_1672446': 'RPL11', 'ILMN_2291644': 'SIRT5', 'ILMN_1676625': 'SS18L1', 'ILMN_1667050': 'PRPS1', 'ILMN_1776088': 'NAT9', 'ILMN_1770641': 'KLHL3', 'ILMN_1718718': 'MKKS', 'ILMN_3235593': 'ZNF841', 'ILMN_1797698': 'RBM12', 'ILMN_1735347': 'MCEE', 'ILMN_1688098': 'TBC1D4', 'ILMN_1784847': 'CREBZF', 'ILMN_1722423': 'SHPRH', 'ILMN_1689665': 'NAE1', 'ILMN_2147993': 'ZNF23', 'ILMN_1658283': 'RPL17', 'ILMN_1753782': 'ZNF266', 'ILMN_1758633': 'CCDC130', 'ILMN_1700915': 'BMI1', 'ILMN_1791388': 'ZNF787', 'ILMN_1679134': 'NSMCE4A', 'ILMN_2266595': 'LILRA5', 'ILMN_1751425': 'ERMP1', 'ILMN_1776653': 'SCML1', 'ILMN_2405684': 'BIRC3', 'ILMN_1812312': 'NDUFS4', 'ILMN_1667260': 'MAPK3', 'ILMN_1748819': 'MRPL22', 'ILMN_1768973': 'HIST2H2AC', 'ILMN_1693635': 'TSPYL2', 'ILMN_2293692': 'CREBBP', 'ILMN_2338785': 'RPS14', 'ILMN_2316540': 'MRPL11', 'ILMN_1694742': 'RPS29', 'ILMN_1715392': 'PRPF3', 'ILMN_1753534': 'RPS18', 'ILMN_2162328': 'PTS', 'ILMN_1665797': 'CSE1L', 'ILMN_2045729': 'WDR12', 'ILMN_1792497': 'AGFG1', 'ILMN_1791069': 'ZNF513', 'ILMN_1660292': 'MRPS21', 'ILMN_1805902': 'CELA1', 'ILMN_1800573': 'RPS21', 'ILMN_2218450': 'LSM1', 'ILMN_1681118': 'CAPRIN2', 'ILMN_1703049': 'AKAP7', 'ILMN_2103547': 'GOLGA8B', 'ILMN_2151818': 'PSMA6', 'ILMN_1809963': 'RSAD1', 'ILMN_1700955': 'TCTEX1D2', 'ILMN_1779324': 'GZMA', 'ILMN_1688423': 'FCER1A', 'ILMN_1755883': 'RPS27A', 'ILMN_1730809': 'SLC29A2', 'ILMN_1795822': 'DIS3L', 'ILMN_2139943': 'RPS3A', 'ILMN_2316104': 'IQCB1', 'ILMN_1775192': 'BCLAF1', 'ILMN_2331890': 'RPL41', 'ILMN_1703697': 'LANCL1', 'ILMN_1719622': 'RABEP1', 'ILMN_1778836': 'SRSF7', 'ILMN_1753312': 'PLXDC2', 'ILMN_1736340': 'ANGEL2', 'ILMN_2094952': 'NUAK2', 'ILMN_2112402': 'PHF5A', 'ILMN_1751692': 'ZNF17', 'ILMN_2117623': 'PLXNC1', 'ILMN_2337241': 'RPS15A', 'ILMN_1665964': 'GAB2', 'ILMN_1789266': 'CCDC25', 'ILMN_1678805': 'POMT2', 'ILMN_1796179': 'HIST1H2BK', 'ILMN_1756326': 'CKS2', 'ILMN_1695157': 'CA4', 'ILMN_1669210': 'SNORD16', 'ILMN_1786050': 'RBBP9', 'ILMN_1656691': 'FBXO4', 'ILMN_1712888': 'HSPH1', 'ILMN_2200917': 'SLC4A7', 'ILMN_1740512': 'TMSB15B', 'ILMN_1765371': 'LUC7L', 'ILMN_1694233': 'ACYP1', 'ILMN_1797318': 'HSPA14', 'ILMN_1665205': 'ZNF260', 'ILMN_1689774': 'MRFAP1L1', 'ILMN_1713143': 'MRPL3', 'ILMN_3224934': 'PNISR', 'ILMN_1742611': 'C1orf52', 'ILMN_1683533': 'CCDC66', 'ILMN_2321064': 'BAX', 'ILMN_1770020': 'PPIL3', 'ILMN_1682038': 'SNORA25', 'ILMN_2347949': 'G6PD', 'ILMN_1673820': 'HLTF', 'ILMN_2277099': 'YWHAB', 'ILMN_1772506': 'ATP5I', 'ILMN_2208903': 'CD52', 'ILMN_1737611': 'VAMP1', 'ILMN_3248703': 'SNORD99', 'ILMN_1685722': 'EIF4A2', 'ILMN_3226637': 'LOC728743', 'ILMN_3306440': 'NEMP1', 'ILMN_1729033': 'RPL9', 'ILMN_1874689': 'MIR181A2HG', 'ILMN_3241046': 'MYBL1', 'ILMN_1655377': 'MRPS22', 'ILMN_1682402': 'SNORD46', 'ILMN_1725105': 'EEF1E1', 'ILMN_1667418': 'TMEM114', 'ILMN_2394576': 'FBXW11', 'ILMN_2058795': 'CPQ', 'ILMN_2324056': 'GNL3', 'ILMN_1688346': 'ZNF800', 'ILMN_1702231': 'C1orf54', 'ILMN_2184789': 'HSCB', 'ILMN_1702763': 'ZMYM1', 'ILMN_1861376': 'PLXDC2', 'ILMN_1714444': 'KLF12', 'ILMN_1764549': 'UBE3A', 'ILMN_1681340': 'HSPB11', 'ILMN_1690371': 'MRPL11', 'ILMN_1745573': 'TTC13', 'ILMN_1656791': 'RPS6', 'ILMN_1673138': 'ZBTB33', 'ILMN_1761058': 'ACAD11', 'ILMN_1706238': 'CSE1L', 'ILMN_2409078': 'SNHG10', 'ILMN_1753190': 'ERCC6L2', 'ILMN_1725366': 'SLC27A5', 'ILMN_1685009': 'ITGAM', 'ILMN_1794038': 'FAM49A', 'ILMN_1713189': 'KANSL2', 'ILMN_2305721': 'POMT1', 'ILMN_1753567': 'ZNF451', 'ILMN_1680967': 'SARNP', 'ILMN_1724474': 'CARD16', 'ILMN_1653469': 'RPL12', 'ILMN_2398274': 'PYCARD', 'ILMN_2057573': 'ESYT2', 'ILMN_3275580': 'ZCCHC18', 'ILMN_1714700': 'TRIB2', 'ILMN_1702858': 'ADHFE1', 'ILMN_1677768': 'POR', 'ILMN_2160819': 'RPS27', 'ILMN_2093500': 'ZBED5', 'ILMN_1722206': 'MAF', 'ILMN_2415722': 'RPS29', 'ILMN_1747251': 'LTB4R', 'ILMN_1781906': 'RBM17', 'ILMN_2364700': 'ENSA', 'ILMN_1652929': 'POGZ', 'ILMN_1719032': 'LSM3', 'ILMN_1789809': 'RPL13AP6', 'ILMN_1768391': 'ARL4C', 'ILMN_1760245': 'TMEM42', 'ILMN_1685824': 'B4GALT5', 'ILMN_2296950': 'APOBEC3F', 'ILMN_1778991': 'NFIB', 'ILMN_2331205': 'CHKB', 'ILMN_1737146': 'TRAM1', 'ILMN_1664920': 'C19orf12', 'ILMN_3251742': 'ZNF322', 'ILMN_1796316': 'MMP9', 'ILMN_1728605': 'TTC3', 'ILMN_1803676': 'ENOSF1', 'ILMN_1696133': 'EPT1', 'ILMN_1703279': 'CXorf57', 'ILMN_2318733': 'BNIP1', 'ILMN_1751378': 'RARS', 'ILMN_2305544': 'DBI', 'ILMN_1793829': 'TMCO1', 'ILMN_3249538': 'SNORA2B', 'ILMN_1656840': 'VPS13D', 'ILMN_1686954': 'RPS10', 'ILMN_1673682': 'GATAD2A', 'ILMN_2243516': 'C11orf63', 'ILMN_1790689': 'CRISPLD2', 'ILMN_1680675': 'MRRF', 'ILMN_1682081': 'RNF19B', 'ILMN_1711270': 'SUGP2', 'ILMN_1707286': 'PLBD1', 'ILMN_1783448': 'DYNC1LI2', 'ILMN_2120273': 'AP1S2', 'ILMN_1751338': 'NUP133', 'ILMN_1778845': 'FAM111A', 'ILMN_1670420': 'METAP2', 'ILMN_1737462': 'OXR1', 'ILMN_2070072': 'RPS7', 'ILMN_1716441': 'SNORD4A', 'ILMN_3245380': 'ZNF860', 'ILMN_1696463': 'SPI1', 'ILMN_1794914': 'UBTD1', 'ILMN_1662334': 'DNAJA3', 'ILMN_1710863': 'GATAD1', 'ILMN_1683969': 'FKBP1A', 'ILMN_1740927': 'LYRM4', 'ILMN_2114876': 'RPL11', 'ILMN_2333367': 'FKBP1A', 'ILMN_1704619': 'VPS29', 'ILMN_1695868': 'PRICKLE4', 'ILMN_2221673': 'ASNSD1', 'ILMN_1670130': 'ARID3A', 'ILMN_1797893': 'N4BP2L2', 'ILMN_2128967': 'C11orf1', 'ILMN_1706779': 'LIG1', 'ILMN_3307276': 'HTATSF1P2', 'ILMN_1739770': 'MED7', 'ILMN_1677532': 'TARDBP', 'ILMN_1664614': 'FAU', 'ILMN_1691181': 'TMX1', 'ILMN_2256359': 'ZNF823', 'ILMN_3300358': 'ZNF84', 'ILMN_2234956': 'LEPR', 'ILMN_1798163': 'UPF3B', 'ILMN_1787511': 'THUMPD2', 'ILMN_3240236': 'SMCR5', 'ILMN_2219712': 'HMGB2', 'ILMN_1741264': 'MRPS33', 'ILMN_1733110': 'RASSF7', 'ILMN_1722838': 'MRPL46', 'ILMN_1691798': 'ZNF26', 'ILMN_1733703': 'TRMU', 'ILMN_1804277': 'SPRED1', 'ILMN_1759419': 'ILVBL', 'ILMN_1739641': 'MTMR3', 'ILMN_3307616': 'EPHA10', 'ILMN_3239925': 'PP7080', 'ILMN_1764415': 'ZNF585A', 'ILMN_1745994': 'GAS7', 'ILMN_1732053': 'SNRNP70', 'ILMN_1668498': 'CWF19L2', 'ILMN_1688666': 'HIST1H2BH', 'ILMN_1701839': 'EXOSC1', 'ILMN_2112730': 'SLC9A4', 'ILMN_2229242': 'LSM3', 'ILMN_3248218': 'SNORD104', 'ILMN_1655765': 'MRPS21', 'ILMN_1722186': 'NDUFAF7', 'ILMN_2346137': 'ZNF557', 'ILMN_2111229': 'TSPOAP1', 'ILMN_1753010': 'GATB', 'ILMN_1659054': 'CHKB', 'ILMN_1656913': 'MDH1', 'ILMN_1756220': 'DDX18', 'ILMN_2217809': 'TMEM126A', 'ILMN_1772487': 'SUGP2', 'ILMN_1777096': 'TDG', 'ILMN_1807994': 'PCNP', 'ILMN_2130514': 'FAM76B', 'ILMN_1690386': 'KAT14', 'ILMN_1815705': 'LZTFL1', 'ILMN_1660847': 'PFKFB3', 'ILMN_1773935': 'TMEM165', 'ILMN_1720440': 'HELQ', 'ILMN_1766803': 'TUBGCP6', 'ILMN_1724376': 'ERLEC1', 'ILMN_1807234': 'ZNF700', 'ILMN_2200503': 'NIT2', 'ILMN_1707088': 'DENND2D', 'ILMN_2386818': 'URGCP', 'ILMN_1741572': 'AKAP8', 'ILMN_1793549': 'PTPN4', 'ILMN_2073289': 'MTSS1', 'ILMN_1764813': 'B3GLCT', 'ILMN_1662658': 'PUS1', 'ILMN_1812191': 'C12orf57', 'ILMN_1764851': 'TP53RK', 'ILMN_1655329': 'RIOK2', 'ILMN_3248773': 'SNHG15', 'ILMN_1713369': 'RPL13A', 'ILMN_1753890': 'TMEM97', 'ILMN_1812559': 'SLC7A6', 'ILMN_1669516': 'ZSCAN9', 'ILMN_3240524': 'MFSD6', 'ILMN_1706075': 'SF3B1', 'ILMN_2251978': 'PAXBP1', 'ILMN_1726659': 'THOP1', 'ILMN_1805658': 'LTV1', 'ILMN_2124816': 'ZNF34', 'ILMN_2193443': 'TRIM16L', 'ILMN_1691341': 'IL7R', 'ILMN_2187487': 'HEATR5B', 'ILMN_1724990': 'ELP6', 'ILMN_2168217': 'GPR183', 'ILMN_1707484': 'GEMIN6', 'ILMN_1741219': 'RRAGB', 'ILMN_2151056': 'BORCS7', 'ILMN_2396786': 'ZNF266', 'ILMN_1733324': 'ITGB3', 'ILMN_2139761': 'LIMCH1', 'ILMN_2333146': 'BCR', 'ILMN_1721621': 'NKTR', 'ILMN_1652490': 'MANSC1', 'ILMN_1808661': 'TOMM5', 'ILMN_1797728': 'HMGCS1', 'ILMN_1708672': 'ACAT2', 'ILMN_3235113': 'TOMM6', 'ILMN_1663220': 'MRPL22', 'ILMN_1714402': 'ZCCHC2', 'ILMN_1715569': 'CCDC53', 'ILMN_1725183': 'TBCE', 'ILMN_1726603': 'ATP5I', 'ILMN_2341952': 'MRPL35', 'ILMN_1687864': 'POP5', 'ILMN_2407464': 'FASTK', 'ILMN_3248270': 'SNORD62B', 'ILMN_1805395': 'LTBP3', 'ILMN_1775708': 'SLC2A3', 'ILMN_1789596': 'ETV6', 'ILMN_1753745': 'HDDC2', 'ILMN_1665384': 'SH3BP5L', 'ILMN_1658160': 'FAM156A', 'ILMN_1660193': 'ZNF529', 'ILMN_2054607': 'CYP4V2', 'ILMN_3241021': 'RNY4', 'ILMN_1734542': 'OVGP1', 'ILMN_1793598': 'APIP', 'ILMN_1745242': 'PLSCR1', 'ILMN_1695357': 'SPDL1', 'ILMN_1651819': 'GALNT11', 'ILMN_1782743': 'LETMD1', 'ILMN_1690049': 'NGDN', 'ILMN_2171384': 'CXCL5', 'ILMN_1708728': 'H2AFJ', 'ILMN_3247998': 'STAP1', 'ILMN_1689097': 'NAA20', 'ILMN_1810267': 'DNHD1', 'ILMN_1657455': 'CEACAM4', 'ILMN_1757287': 'MAPK6', 'ILMN_1802458': 'AGTRAP', 'ILMN_1679071': 'MTX3', 'ILMN_1693145': 'BUB3', 'ILMN_1743299': 'PEX2', 'ILMN_1740441': 'CYB5R3', 'ILMN_2413537': 'HEMGN', 'ILMN_1704557': 'RPS6KB1', 'ILMN_1735552': 'KIF1B', 'ILMN_1807596': 'UBAP1', 'ILMN_1663532': 'RIC8B', 'ILMN_1732176': 'AGPAT2', 'ILMN_1741440': 'SLC35A1', 'ILMN_1732688': 'DUT', 'ILMN_2160388': 'RPL24', 'ILMN_1691104': 'PGAM4', 'ILMN_1766411': 'AP1S2', 'ILMN_2123557': 'MIGA1', 'ILMN_1679339': 'C3orf62', 'ILMN_1778236': 'PTPN11', 'ILMN_2232936': 'UQCRH', 'ILMN_2215211': 'ZNF514', 'ILMN_1770378': 'ANAPC10', 'ILMN_1680072': 'ZNF32', 'ILMN_1699160': 'ITK', 'ILMN_1656934': 'REPS2', 'ILMN_2047599': 'TMEM50B', 'ILMN_1658373': 'PAN2', 'ILMN_1781952': 'MGST1', 'ILMN_2410038': 'FAM111A', 'ILMN_1813544': 'OXCT1', 'ILMN_1846306': 'LOC105379362', 'ILMN_2144426': 'HIST2H2AA3', 'ILMN_1785202': 'STAT4', 'ILMN_1730082': 'RPUSD4', 'ILMN_1706523': 'FCGR2A', 'ILMN_1734205': 'RASSF1', 'ILMN_1663618': 'STAT3', 'ILMN_1726839': 'DCUN1D5', 'ILMN_2319994': 'RPL3', 'ILMN_1791332': 'ATP5O', 'ILMN_1727281': 'TAF6L', 'ILMN_1727134': 'KLHL42', 'ILMN_3187470': 'BTNL10', 'ILMN_2110532': 'RPL26L1', 'ILMN_1789535': 'DHDDS', 'ILMN_2345739': 'CAPRIN2', 'ILMN_2106265': 'GDPD1', 'ILMN_1713454': 'ZNF671', 'ILMN_3251482': 'ALG10B', 'ILMN_2072296': 'CKS2', 'ILMN_2191568': 'NPRL2', 'ILMN_2134062': 'ALKBH3', 'ILMN_2094718': 'TPT1', 'ILMN_1705201': 'FOXC2', 'ILMN_1892403': 'SNORD13', 'ILMN_3244110': 'FAM156B', 'ILMN_1670172': 'WDR33', 'ILMN_1708382': 'ELP6', 'ILMN_1742521': 'GRB2', 'ILMN_1665331': 'AMT', 'ILMN_2352245': 'RASSF6', 'ILMN_1783728': 'TBRG4', 'ILMN_1808613': 'CRELD1', 'ILMN_2203807': 'MRPL57', 'ILMN_1773968': 'SERBP1', 'ILMN_1675523': 'PLPP2', 'ILMN_1658416': 'MRPS18C', 'ILMN_1738767': 'PLP2', 'ILMN_2363634': 'ADHFE1', 'ILMN_1744835': 'MRPL21', 'ILMN_1724422': 'SELL', 'ILMN_1791838': 'LYG1', 'ILMN_1762549': 'ORAOV1', 'ILMN_2317348': 'APTX', 'ILMN_2301624': 'MACF1', 'ILMN_1796962': 'PPP3R1', 'ILMN_1728230': 'ZNF30', 'ILMN_1719205': 'FBL', 'ILMN_2200659': 'SNHG5', 'ILMN_1677385': 'SMIM19', 'ILMN_1793525': 'KIR2DS3', 'ILMN_1661293': 'ZNF224', 'ILMN_2190851': 'PPID', 'ILMN_1738243': 'RPS29', 'ILMN_3223798': 'ZNF84', 'ILMN_1780397': 'TRAF3IP3', 'ILMN_1755364': 'RALA', 'ILMN_3305339': 'UBA5', 'ILMN_1739942': 'FAM117B', 'ILMN_1724533': 'LY96', 'ILMN_3244157': 'SNORD83B', 'ILMN_1653618': 'ZZZ3', 'ILMN_1666715': 'WHSC1L1', 'ILMN_2410986': 'STAT3', 'ILMN_2053538': 'RHBDL2', 'ILMN_1778203': 'CLN5', 'ILMN_1768784': 'PSMC2', 'ILMN_3224204': 'PSMG4', 'ILMN_1800626': 'SESN1', 'ILMN_2411723': 'RPSA', 'ILMN_1672366': 'PIGY', 'ILMN_1665095': 'NSMF', 'ILMN_3208973': 'RPSAP9', 'ILMN_1898124': 'SNHG15', 'ILMN_1751898': 'C12orf4', 'ILMN_2093389': 'SNAPC1', 'ILMN_1693210': 'NSMCE2', 'ILMN_3249406': 'URB2', 'ILMN_1685057': 'SLC22A4', 'ILMN_2144574': 'CTBS', 'ILMN_1772722': 'MRPS33', 'ILMN_1766359': 'GATAD2B', 'ILMN_1715661': 'TFAM', 'ILMN_2332558': 'ARL5A', 'ILMN_2352563': 'CLDND1', 'ILMN_1811702': 'GRN', 'ILMN_1724504': 'SETD3', 'ILMN_2344002': 'GEMIN2', 'ILMN_1690125': 'PDLIM7', 'ILMN_2093748': 'ZNF669', 'ILMN_2407669': 'PEAR1', 'ILMN_1775677': 'TYSND1', 'ILMN_1679917': 'ARL16', 'ILMN_2330267': 'ABCE1', 'ILMN_1728478': 'CXCL16', 'ILMN_1785141': 'MICAL2', 'ILMN_2354381': 'PON2', 'ILMN_1766425': 'REPS2', 'ILMN_1657554': 'TSPYL2', 'ILMN_3245869': 'SMIM4', 'ILMN_1657722': 'RPS3A', 'ILMN_1659077': 'CD40LG', 'ILMN_1775405': 'ARL4A', 'ILMN_1748109': 'PEX1', 'ILMN_1802669': 'PPP3CB', 'ILMN_2356311': 'SMIM11A', 'ILMN_1797181': 'LOC93622', 'ILMN_2364828': 'OGT', 'ILMN_1752758': 'BTN2A2', 'ILMN_1701854': 'GNG5', 'ILMN_3251506': 'ZNF69', 'ILMN_2381121': 'UQCC1', 'ILMN_2356284': 'PFDN5', 'ILMN_1725312': 'RASA1', 'ILMN_3249742': 'PXMP4', 'ILMN_1712320': 'DDX50', 'ILMN_1784410': 'UBP1', 'ILMN_1714592': 'CDA', 'ILMN_1717809': 'RNF24', 'ILMN_2307656': 'AGTRAP', 'ILMN_1736888': 'SAR1B', 'ILMN_1682857': 'NDUFAF2', 'ILMN_1713031': 'CPQ', 'ILMN_1807945': 'ANP32A', 'ILMN_1682095': 'RCOR3', 'ILMN_1662973': 'CD82', 'ILMN_1713124': 'AKR1C3', 'ILMN_1739257': 'EIF3E', 'ILMN_2405797': 'REPS2', 'ILMN_1724837': 'ZC3HAV1', 'ILMN_2175131': 'TMEM14C', 'ILMN_3246869': 'SCARNA21', 'ILMN_2134855': 'PIN4P1', 'ILMN_2184373': 'CXCL8', 'ILMN_2303170': 'MBNL3', 'ILMN_1702265': 'HDHD2', 'ILMN_1751258': 'NDUFA4', 'ILMN_1736901': 'ZDHHC23', 'ILMN_1668851': 'AADACL4', 'ILMN_1782729': 'CLECL1', 'ILMN_1792972': 'ZNF439', 'ILMN_2402341': 'MAPK3', 'ILMN_3209832': 'PET100', 'ILMN_1767320': 'MAPK1', 'ILMN_1711023': 'CDK5RAP1', 'ILMN_2041046': 'CKS1B', 'ILMN_1679483': 'INTS10', 'ILMN_1788468': 'ARGLU1', 'ILMN_1811574': 'MAPK8IP3', 'ILMN_2066124': 'AFG3L2', 'ILMN_3241218': 'ANKIB1', 'ILMN_1691131': 'NAA38', 'ILMN_1652409': 'SPATA7', 'ILMN_1742578': 'MKLN1', 'ILMN_1694671': 'ZFAND2A', 'ILMN_1800935': 'ARV1', 'ILMN_1815500': 'ITPR3', 'ILMN_1655635': 'METTL3', 'ILMN_1700306': 'OCIAD2', 'ILMN_1758735': 'NLRP12', 'ILMN_1671893': 'CHMP2A', 'ILMN_1679881': 'WRN', 'ILMN_1664068': 'ERGIC1', 'ILMN_1654552': 'MRPS31', 'ILMN_1661359': 'CXorf65', 'ILMN_1660227': 'LINC00999', 'ILMN_3188984': 'ZFAS1', 'ILMN_1747744': 'LHFPL2', 'ILMN_1762747': 'RPL15', 'ILMN_1763487': 'CTLA4', 'ILMN_2344216': 'STX2', 'ILMN_1813344': 'NDUFAF5', 'ILMN_2147306': 'PNRC2', 'ILMN_1801303': 'AMY2A', 'ILMN_1777344': 'RPS13', 'ILMN_1778173': 'AK3', 'ILMN_2042941': 'TMEM159', 'ILMN_1728626': 'WDR5', 'ILMN_2392717': 'LARP7', 'ILMN_1714956': 'PLA2G12A', 'ILMN_1789614': 'TPT1', 'ILMN_3249235': 'GIN1', 'ILMN_1704055': 'NOP16', 'ILMN_1703989': 'ARFRP1', 'ILMN_2099528': 'BTLA', 'ILMN_1798458': 'KAZN', 'ILMN_1660063': 'POLE4', 'ILMN_3300972': 'SIVA1', 'ILMN_2161357': 'PNISR', 'ILMN_1673638': 'RPS3A', 'ILMN_1751072': 'SRPRB', 'ILMN_1701930': 'EEF1B2', 'ILMN_1753064': 'TTC13', 'ILMN_3308607': 'MIR607', 'ILMN_1783276': 'NEXN', 'ILMN_1695853': 'CLK4', 'ILMN_1678928': 'SLCO3A1', 'ILMN_1658928': 'GNB2', 'ILMN_1810729': 'UBL3', 'ILMN_1679209': 'HSPA9', 'ILMN_2057826': 'PHF3', 'ILMN_1726698': 'PSME1', 'ILMN_1886847': 'ODF2L', 'ILMN_1758146': 'SIRPA', 'ILMN_2392356': 'CTPS2', 'ILMN_1697559': 'G6PD', 'ILMN_2070477': 'TAF8', 'ILMN_1691861': 'FASTK', 'ILMN_2206272': 'D2HGDH', 'ILMN_1701596': 'RPS20', 'ILMN_2393573': 'RASSF1', 'ILMN_1666208': 'MIS18BP1', 'ILMN_1796235': 'UTP4', 'ILMN_1772286': 'OCIAD2', 'ILMN_1655622': 'THAP12', 'ILMN_1782247': 'KAT2A', 'ILMN_2335669': 'ZC3H14', 'ILMN_3244343': 'SNORA21', 'ILMN_1754303': 'RPL30', 'ILMN_1711862': 'RNF7', 'ILMN_2414848': 'TBRG4', 'ILMN_1736021': 'PRPF4B', 'ILMN_1777745': 'FAM133B', 'ILMN_1653794': 'SNHG5', 'ILMN_1738173': 'METTL4', 'ILMN_3306950': 'CDK10', 'ILMN_2209515': 'SNORD56', 'ILMN_2123415': 'BMP8B', 'ILMN_2225735': 'CRBN', 'ILMN_2181125': 'NAPB', 'ILMN_1694075': 'GADD45A', 'ILMN_1790354': 'RABGGTB', 'ILMN_2270299': 'TP53BP2', 'ILMN_1663195': 'MCM7', 'ILMN_1672004': 'TOB1', 'ILMN_1786189': 'NIFK', 'ILMN_1781795': 'ERH', 'ILMN_1815924': 'NUP107', 'ILMN_2131880': 'DPY30', 'ILMN_1706149': 'PDCD2L', 'ILMN_2215640': 'TUBA3D', 'ILMN_1765880': 'USB1', 'ILMN_1722894': 'ZNRD1', 'ILMN_2252160': 'UBC', 'ILMN_1659017': 'C11orf74', 'ILMN_2182647': 'PINX1', 'ILMN_2348503': 'PPIE', 'ILMN_1786429': 'LPAR6', 'ILMN_1695000': 'TFIP11', 'ILMN_1747223': 'FRYL', 'ILMN_1791840': 'RALBP1', 'ILMN_1727361': 'LEMD3', 'ILMN_2372403': 'ALDH5A1', 'ILMN_1808898': 'NPR2', 'ILMN_1723235': 'DUS3L', 'ILMN_3248781': 'SDHAP2', 'ILMN_1680703': 'MRPS15', 'ILMN_1776104': 'NDUFS5', 'ILMN_2320250': 'NOL6', 'ILMN_2391141': 'UBE3A', 'ILMN_2105253': 'PTGR2', 'ILMN_1664776': 'EFR3A', 'ILMN_1671568': 'ECHDC2', 'ILMN_2182198': 'MRPL58', 'ILMN_2367418': 'OSCAR', 'ILMN_1682799': 'STAMBPL1', 'ILMN_1730773': 'SNORA70', 'ILMN_3307791': 'FAM69A', 'ILMN_3248443': 'SNHG6', 'ILMN_3251737': 'EEF1A1', 'ILMN_1799728': 'ADAM15', 'ILMN_1811221': 'SLC5A8', 'ILMN_1656393': 'PPP2R3A', 'ILMN_1736048': 'ELL', 'ILMN_1797933': 'MRPL17', 'ILMN_1663577': 'S100PBP', 'ILMN_3236970': 'LINC00667', 'ILMN_1671895': 'ZNF613', 'ILMN_1666739': 'RBM15', 'ILMN_1682738': 'SMAD3', 'ILMN_1801869': 'WDR75', 'ILMN_1796336': 'MAP1S', 'ILMN_1672389': 'CRYZ', 'ILMN_3229552': 'MED7'

In [ ]:
# Rename the gene IDs to gene symbol using the dict 
filt_genes.rename(index=gene_id_to_symbol, inplace=True)
filt_genes.head()

         IG_value
A1BG     0.082485
RBFOX1   0.079398
A3GALT2  0.176929
AADAC    0.073541
AADACL4  0.179462

In [ ]:
# # Save the filtered genes with their IG values
# filt_genes.to_csv("../data/GSE252168/IG_results_v2", sep="\t")